version: '3'

services:
  influxdb:
    build:
      context: . # The path to the Dockerfile for influxdb-arm
      dockerfile: influxdb
    container_name: influxdb
    volumes:
      - influxdb:/var/lib/influxdb2 # The volume for influxdb data
    ports:
      - 8086:8086 # The port for influxdb HTTP API
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup # The environment variables for influxdb configuration
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin54321
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=speedtest
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

  speedtest:
    build:
      context: . # The path to the Dockerfile for speedtest-influxdb
      dockerfile: speedtest
    container_name: speedtest
    depends_on:
      - speedtest-influxdb # The dependency on influxdb-arm service
    environment:
      - INFLUXDB_URL=http://speedtest-influxdb:8086 # The environment variables for speedtest-influxdb configuration
      - INFLUXDB_DB=speedtest
      - INFLUXDB_USER=admin
      - INFLUXDB_PWD=admin54321

  grafana:
    build:
      context: . # The path to the Dockerfile for grafana-influxdb
      dockerfile: grafana
    container_name: grafana
    depends_on:
      - speedtest-influxdb # The dependency on influxdb-arm service
    ports:
      - 3000:3000 # The port for grafana web interface
    volumes:
      - grafana:/var/lib/grafana # The volume for grafana data

volumes:
  influxdb: # The named volume for influxdb data
  grafana: # The named volume for grafana data
